#!/usr/bin/env bash
# OSI model meaning & How is the OSI model organized
What is the OSI model?
2- The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology.

How is the OSI model organized?
2- From the lowest to the highest level. The seven layers, in ascending order, are: Physical, Data Link, Network, Transport, Session, Presentation, and Application.
